site_name: HAADIC
site_url: https://patarimi.github.io/haadic
watch:
  - haadic

nav:
  - Home: README.md
  - CLI-Command: CLI-ref.md

theme:
  name: material
  features: ['navigation.indexes']
  
markdown_extensions:
  - toc:
      permalink: True
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - cyclopts
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
  - api-autonav:
      modules: ['haadic']
      nav_section_title: "Module Documentation"
      exclude: ['haadic.data', 'haadic.main']
