site_name: HAADIC
site_url: https://patarimi.github.io/haadic
repo_url: https://github.com/Patarimi/haadic
watch:
  - haadic

nav:
  - Home: README.md
  - CLI-Command: CLI-ref.md

theme:
  name: material
  features: ['navigation.indexes']
  
markdown_extensions:
  - toc:
      permalink: True
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - cyclopts
  - mkdocstrings:
      handlers:
        python:
          paths: [haadic]
          options:
            docstring_style: sphinx
            show_source: false
            show_root_heading: true
            show_root_full_path: false
  - api-autonav:
      modules: ['haadic']
      nav_section_title: "Module Documentation"
      on_implicit_namespace_package: 'skip'
      exclude: ['haadic.main']
