[project]
name = "haadic"
version = "0.6.0"
description = "A package for parametric layout design."
authors = [{name = "Patarimi", email="<38954040+Patarimi@users.noreply.github.com>"}]
readme = "docs/README.md"
requires-python = ">3.11,<3.14"
dependencies = [
    "ciel>=2.2.0",
    "cyclopts>=3.22.3",
    "klayout>=0.30.2",
    "lark>=1.2.2",
    "matplotlib>=3.10.3",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "pydantic>=2.11.7",
    "pyqt6>=6.11.0 ; sys_platform == 'linux'",
    "python-dotenv>=1.1.1",
    "pyyaml>=6.0.2",
    "rich>=13.9.4",
    "scikit-rf>=1.8.0",
    "scipy>=1.16.1",
    "tabulate>=0.9.0",
]

[build-system]
requires = ["uv_build>=0.8.3,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[project.scripts]
haadic = "haadic.main:app"

[tool.poe.tasks]
update_show = "uv lock --dry-run --upgrade"
update_all = "uv sync --upgrade --all-groups --all-extras"
test = 'coverage run -m pytest --basetemp=tmp'
cover = "coverage report -m --skip-covered"
publish = "poetry publish --build --username __token__ --password $PYPI_TOKEN"
doc = "mkdocs build"

[tool.poe.tasks.lint]
sequence = [
    {cmd = "uvx ruff format"},
    {cmd = "uvx ruff check"},
    {cmd = "uvx ty check"},
]

[tool.poe.tasks.precommit]
sequence = [
    {ref = "update_all"},
    {ref = "lint"},
    {ref = "doc"},
    {ref = "test"},
    {ref = "cover"}
]

[tool.ruff]
extend-include = ["./workdir/*.py"]

[tool.pytest.ini_options]
testpaths = ["tests"]
log_cli_level = "ERROR"
log_file_level = "INFO"
log_file = "./pytest.log"

[dependency-groups]
dev = [
    "coverage>=7.10.6",
    "poethepoet>=0.36.0",
    "pytest>=8.4.1",
]
doc = [
    "cyclopts[mkdocs]>=4.4.1",
    "mkdocs>=1.6.1",
    "mkdocs-api-autonav>=0.4.0",
    "mkdocs-material>=9.6.16",
]


[tool.ty.src]
exclude = ["haadic/wrappers/oems.py", "haadic/wrappers/ngsolve_w.py"]
