[project]
name = "haadic"
version = "0.6.0"
description = "A package for parametric layout design."
authors = [{name = "Patarimi", email="<38954040+Patarimi@users.noreply.github.com>"}]
readme = "docs/README.md"
requires-python = ">3.12,<3.14"
dependencies = [
    "ciel>=2.6.0",
    "cyclopts>=4.22.0",
    "klayout>=0.30.2",
    "lark>=1.2.2",
    "matplotlib>=3.11.1",
    "numpy>=2.5.0",
    "pandas>=3.0.0",
    "pydantic>=2.13.4",
    "pyqt6>=6.11.0 ; sys_platform == 'linux'",
    "python-dotenv>=1.1.1",
    "rich>=13.9.4",
    "scikit-rf>=1.12.0",
    "scipy>=1.18.0",
    "tabulate>=0.9.0",
]

[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[project.scripts]
haadic = "haadic.main:app"

[tool.poe.tasks]
update_show = "uv lock --dry-run --upgrade"
update_all = "uv sync --upgrade --all-groups --all-extras"
test = 'pytest --basetemp=tmp'
cover = "pytest --basetemp=tmp --cov-report term-missing:skip-covered --cov=haadic -n auto"
publish = "poetry publish --build --username __token__ --password $PYPI_TOKEN"
doc = "mkdocs build"

[tool.poe.tasks.lint]
sequence = [
    {cmd = "uvx ruff format"},
    {cmd = "uvx ruff check"},
    {cmd = "uvx ty check"},
]

[tool.poe.tasks.precommit]
sequence = [
    {ref = "update_all"},
    {ref = "lint"},
    {ref = "doc"},
    {ref = "cover"}
]

[tool.ruff]
extend-include = ["./workdir/*.py"]
extend-exclude = ["haadic/data/template/*/design.py"]
lint.extend-select = ["D"]
lint.extend-ignore = ["D203", "D212"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D"]

[tool.pytest.ini_options]
testpaths = ["tests"]
log_cli_level = "ERROR"
log_file_level = "INFO"
log_file = "./pytest.log"

[dependency-groups]
dev = [
    "poethepoet>=0.48.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-xdist>=3.8.0",
]
doc = [
    "cyclopts[mkdocs]>=4.22.0",
    "mkdocs>=1.6.1",
    "mkdocs-api-autonav>=0.4.0",
    "mkdocs-material>=9.7.7",
]


[tool.ty.src]
exclude = ["haadic/io/wrappers/oems.py", "haadic/io/wrappers/ngsolve_w.py", "haadic/data/template/*/design.py"]
