[project]
name = "hades"
version = "0.4.1"
description = "A package for parametric layout design."
authors = [{name = "Patarimi", email="<38954040+Patarimi@users.noreply.github.com>"}]
readme = "docs/README.md"
requires-python = ">3.11,<3.14"
dependencies = [
    "cyclopts>=3.22.3",
    "klayout>=0.30.2",
    "lark>=1.2.2",
    "matplotlib>=3.10.3",
    "ngsolve==6.2.2503",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
    "pyyaml>=6.0.2",
    "rich>=13.9.4",
    "scikit-rf>=1.8.0",
    "scipy>=1.16.1",
    "volare>=0.20.6",
]

[build-system]
requires = ["uv_build>=0.8.3,<0.9.0"]
build-backend = "uv_build"
[tool.uv.build-backend]
module-root = ""

[project.scripts]
hades = "hades.main:app"

[tool.poe.tasks]
update_show = "poetry show -T -o --with=dev,doc"
update_all = "poetry update --with=doc,dev"
test = 'pytest --basetemp=tmp'
install_all = "poetry install --with=dev,doc"
publish = "poetry publish --build --username __token__ --password $PYPI_TOKEN"
doc = "mkdocs gh-deploy"
run = "wsl -d NixOS nix-shell --run"
smoke_test = ["run magic"]

[tool.poe.tasks.precommit]
sequence = [
    {ref = "update_show"},
    {cmd = "ruff format"},
    {cmd = "ruff check"},
    {ref = "test"}
]

[tool.pytest.ini_options]
testpaths = ["tests"]
log_cli_level = "ERROR"
log_file_level = "INFO"
log_file = "./pytest.log"

[dependency-groups]
dev = [
    "poethepoet>=0.36.0",
    "pytest>=8.4.1",
    "pytest-sugar>=1.0.0",
]
doc = [
    "mkdocs>=1.6.1",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-literate-nav>=0.6.2",
    "mkdocs-material>=9.6.16",
    "mkdocs-section-index>=0.3.10",
    "mkdocs-typer>=0.0.3",
    "mkdocstrings>=0.30.0",
    "mkdocstrings-python>=1.16.12",
]
