"""Contains the main entry point of the haadic package, which is the command line interface (CLI) defined using the cyclopts library. It also contains some utility functions for the CLI commands."""

from datetime import datetime
import logging
import os
from typing import Optional
from cyclopts import App
from pathlib import Path

from haadic._config import DATA_DIR
from haadic.core.steps.step import cleanup, Dim
from haadic.core import techno
from haadic.design.components.ekv import EKV

# Skip logging configuration if it is already done (eg during tests)
log_path = os.path.join(os.path.curdir, "haadic.log")
if not logging.getLogger().hasHandlers():
    logging.basicConfig(
        level=logging.INFO,
        handlers=[
            logging.FileHandler(log_path),
            logging.StreamHandler(),
        ],
        format="|%(levelname)-7s| %(filename)s:%(lineno)d | %(message)s",
    )

app = App(name="haadic")
app.command(techno.pkd_app)

app.command(cleanup, name="clean")


@app.command(name="smoke-test")
def smoke_test_cli():
    """Run a 'smoke test' to check if haadic is installed correctly."""
    from haadic.io.wrappers.tools import nix_check

    if not nix_check():
        raise SystemError(f"Error during nix check. Please check {log_path}.")
    logging.info("haadic installed correctly !")


@app.command(name="run")
def run_cli(
    design_py: Path = Path("design.py"),
    sub_folder: Optional[Path] = None,
    timestamp: bool = False,
    reload_result: Optional[bool] = None,
    sweep_folder: bool = False,
) -> Dim:
    r"""Run the full haadic flow.

    It runs the following steps :\n
        - Generate the layout using the specified technology.\n
        - Extract equivalent spice schematic.\n
        - Run test benches.\n
        - Compute circuit performances.\n

    :param design_py: a python file with at least the following function : layout, bench, evaluate.
    :param sub_folder: All files generated by the flow are stored inside this folder. Default "./results/design"
    :param timestamp: If true, a new folder named <sub_folder>_<current_time> is created and the flow is run inside it.
    :param reload_result: If true, try to reload results. Else, run the full flow and recompute everything.
    :param sweep_folder: If true, create a new folder for each sweep parameter value.
    :return: Nothing.
    """
    from haadic.core.flow import Flow
    from haadic.core.steps.step import import_or_default

    design = import_or_default(design_py, Flow.__dataclass_fields__.keys())
    design = Flow(**design)
    design.config.run_dir = (
        sub_folder if sub_folder is not None else Path("./results") / design_py.stem
    )
    if timestamp:
        design.config.run_dir = Path(
            f"{design.config.run_dir.name}_{datetime.now().strftime('%Y-%m-%d_%H_%M_%S')}"
        )
    logging.info(f"Running design {design_py} in {design.config.run_dir}")
    design.benches = [
        bench if bench.is_absolute() else Path(design_py).parent / bench
        for bench in design.benches
    ]
    if reload_result is not None:
        design.config.reload = reload_result
    design.config.sweep_folder = sweep_folder

    input = import_or_default(Path(design_py), {"local_model", "target", "dimensions"})
    logging.info(
        "design parameters:\n\t"
        + "\n\t".join([f"{k}: {v}" for k, v in design.__dict__.items()])
    )
    if "dimensions" in input and len(input["dimensions"].dct) > 0:
        return design.run_from_dim(input["dimensions"])
    if "local_model" in input and "target" in input:
        return design.run_from_target(input["target"], input["local_model"])
    raise ValueError(
        "Please provides either a local_model and a target or a set of dimensions."
    )


@app.command(name="extract-ekv")
def extract_ekv_cli(
    techno_name: techno.Available_PDK,
    output: Optional[Path] = None,
    rf: bool = True,
    force: bool = False,
) -> EKV:
    """Extract EKV model parameters from a given technology and save them in a json file.

    :param techno_name: name of the technology to extract the EKV model from. Must be one of the techno supported by haadic.
    :param output: path of the json file to save the extracted model. If None, the model is saved in the pdk install directory with the name ekv_model_<techno_name>.json.
    :param rf: If true, extract the RF parameters of the EKV model. Else, only extract the DC parameters.
    :param force: If true, overwrite the existing model file. Else, skip extraction if the file already exists.
    :return: The extracted EKV model.
    """
    if output is None:
        output = techno.get_file(techno_name, "ekv_model")
        output.parent.mkdir(parents=True, exist_ok=True)
    ekv = EKV(techno=techno_name)
    if not output.is_file() or force:
        logging.info(
            f"Extracting EKV model for {techno_name} and saving it in {output}."
        )
        ekv.extract_model(output.parent, rf=rf)
        ekv.dump(output)
    return ekv


@app.command(name="new")
def template(output_dir: Path = Path(os.curdir), no_input: bool = False) -> None:
    """Create a new project using the haadic template."""
    import subprocess

    template_dir = DATA_DIR / "template"
    cmd = ["uvx", "cookiecutter", template_dir, "--output-dir", output_dir]
    if no_input:
        cmd.append("--no-input")
    subprocess.run(cmd, check=True)
