from typing import Self, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from haadic.io.writers.netlist import Netlist
from haadic.io.wrappers.ngspice import compute
from haadic.io.wrappers.tools import to_wsl
from haadic.core.techno import get_file, load_pdk, Available_PDK
from haadic.core.steps.step import can_skip, Step


@dataclass
class ConfigSim:
    bench: Path = Path("bench.cir")
    techno: Available_PDK = "sky130"

    def __post_init__(self) -> Self:
        if isinstance(self.bench, str):
            self.bench = Path(self.bench)
        return self


@dataclass
class BenchSim(Step):
    config: ConfigSim = field(default_factory=ConfigSim)
    input_suffixes: Sequence[str] = field(default_factory=lambda: [".cir"])
    output_suffix: str = ".raw"

    def run(self, input_file: Path = Path("top.cir")) -> Path:
        """
        Run the given netlist using the requested technologie.

        :param input_file: spice netlist bench to be simulated, defaults to "bench.cir"
        :return Path: path to the output raw file generated by ngspice.
        """
        bench = self.config.bench
        data_file = Path(input_file).with_name(bench.name).with_suffix(self.output_suffix)
        if can_skip(bench, data_file) and can_skip(input_file, data_file):
            return data_file
        techno = self.config.techno

        spice = Netlist().load(bench)
        section = load_pdk(techno).get("section", "tt")
        spice.add_lib(to_wsl(get_file(techno, "lib_spice")), section)

        spice.add_include(input_file)
        spice.write(data_file.with_name(bench.name))

        compute(data_file.with_name(bench.name), data_file)
        return data_file
