"""Spice simulation step for the haadic design flow."""

from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path

from haadic.core.steps.step import Step, can_skip
from haadic.core.techno import Available_PDK, get_file, load_pdk
from haadic.io.handlers.netlist import load_netlist
from haadic.io.wrappers.ngspice import compute


@dataclass
class ConfigSim:
    """
    Configuration for the BenchSim step.

    :param bench: path to the bench file to simulate, defaults to "bench.cir"."
    :param techno: name of the technology to use for the simulation, defaults to "sky130".
    """

    bench: Path = Path("bench.cir")
    techno: Available_PDK = "sky130"


@dataclass
class BenchSim(Step):
    """
    Step to run a spice simulation using ngspice.

    :param config: configuration for the BenchSim step.
    :param input_suffixes: list of accepted input file suffixes for this step, defaults to [".cir"].
    :param output_suffix: suffix for the output file generated by this step, defaults to ".raw".
    """

    config: ConfigSim = field(default_factory=ConfigSim)
    input_suffixes: Sequence[str] = field(default_factory=lambda: [".cir"])
    output_suffix: str = ".raw"

    def run(self, input_file: Path = Path("top.cir")) -> Path:
        """
        Run the given netlist using the requested technologie.

        :param input_file: spice netlist bench to be simulated, defaults to "bench.cir"
        :return Path: path to the output raw file generated by ngspice.
        """
        bench = self.config.bench
        data_file = (
            Path(input_file).with_name(bench.name).with_suffix(self.output_suffix)
        )
        if can_skip(bench, data_file) and can_skip(input_file, data_file):
            return data_file
        techno = self.config.techno

        spice = load_netlist(bench)
        section = load_pdk(techno).get("section", "tt")
        spice.add_lib(get_file(techno, "lib_spice"), section)

        spice.add_include(input_file)

        spice.add_write(data_file)
        spice.write(data_file.with_name(bench.name))

        compute(data_file.with_name(bench.name), data_file.with_suffix(".log"))
        return data_file
