from dataclasses import dataclass, field
from pathlib import Path
from haadic.io.writers.netlist import Netlist
from haadic.io.wrappers.ngspice import compute
from haadic.io.wrappers.tools import to_wsl
from haadic.core.techno import get_file, load_pdk, Available_PDK


class ConfigSim:
    techno: Available_PDK = "sky130"


@dataclass
class Bench:
    config: ConfigSim = field(default_factory=ConfigSim)

    def run(self, bench_name: Path = Path("bench.cir")) -> Path:
        """
        Run the given netlist using the requested technologie.

        :param bench_name: spice netlist bench to be simulated, defaults to "bench.cir"
        :return Path: path to the output raw file generated by ngspice.
        """
        data_file = Path(bench_name).with_suffix(".raw")
        techno = self.config.techno

        spice = Netlist().load(bench_name)
        skip_lib_add = False
        for oth in spice.others:
            if oth.startswith(".lib") and to_wsl(get_file(techno, "lib_spice")) in oth:
                skip_lib_add = True
        if not skip_lib_add:
            section = (
                "tt"
                if "section" not in load_pdk(techno)
                else load_pdk(techno)["section"]
            )
            spice.add_lib(to_wsl(get_file(techno, "lib_spice")), section)
        spice.write(bench_name)

        compute(Path(bench_name), data_file)
        return data_file
