from collections.abc import Callable
import logging
import os
from pathlib import Path
import shutil
from typing import Optional, Self, Sequence

import pandas as pd
from klayout import db
import pydantic
from haadic.io.readers.raw import parse_out
from haadic.design.layouts.tools import LayerStack

default_dict = {"extract": None}


@pydantic.dataclasses.dataclass
class Dim:
    dct: dict[str, float] = pydantic.Field(default_factory=dict)

    def __getitem__(self, key: str) -> float:
        return self.dct[key]

    def __setitem__(self, key: str, value: float) -> None:
        self.dct[key] = float(value)


SimRes = Sequence[pd.DataFrame]


@pydantic.dataclasses.dataclass
class FlowStep:
    layout: (
        Callable[[db.Cell, LayerStack, Dim], None]
        | Callable[[db.Cell, LayerStack], None]
    )
    techno: str
    benches: Sequence[Path]
    evaluate: Optional[Callable] = None
    target: Dim = pydantic.Field(default_factory=Dim)
    local_model: Optional[Callable[[], Dim]] = None
    dimensions: Optional[Dim] = None
    options: dict = pydantic.Field(default_factory=lambda: default_dict)

    @pydantic.model_validator(mode="after")
    def check_model_or_dimensions(self) -> Self:
        if self.local_model is None and self.dimensions is None:
            raise RuntimeError(
                "Please provide a local_model function or a dimensions dict."
            )
        return self


def cleanup(folder: str = "", dry_run: bool = False):
    """
    Remove all files generated by haadic in the specified folder.

    :param folder: path of the folder to clean.
    :param dry_run: if True, only print which files would be removed without actually removing them. Default is False.
    """
    suffix_to_remove = [".gds", ".cir", ".raw", ".log", ".nodes", ".sim", ".tcl"]
    if folder:
        os.chdir(Path(folder))
    for suffix in suffix_to_remove:
        file = Path("top").with_suffix(suffix)
        if file.is_file():
            if dry_run:
                print(f"Would remove file: {file}")
            else:
                os.remove(file)
    directories_to_remove = [
        "extfile",
    ]
    for directory in directories_to_remove:
        dir_path = Path(directory)
        if dir_path.is_dir():
            if dry_run:
                print(f"Would remove directory: {dir_path}")
            else:
                shutil.rmtree(dir_path)


def load_result(data_name: Path | str = "bench.raw") -> pd.DataFrame:
    return parse_out(Path(data_name))


def compare_to(perf: dict, target: dict):
    cost = 0
    for key in target:
        if perf is None or key not in perf:
            logging.warning(f"Key {key} not found in performance dictionary")
            cost += target[key] ** 2
        else:
            cost += (target[key] - perf[key]) ** 2

    return cost
