import json
from functools import reduce
import sys
from typing import Any, Iterable, Protocol, Sequence, Generator
import logging
import os
from pathlib import Path
import shutil

import pydantic


@pydantic.dataclasses.dataclass
class Dim:
    dct: dict[str, float] = pydantic.Field(default_factory=dict)

    def __getitem__(self, key: str) -> float:
        return self.dct[key]

    def __setitem__(self, key: str, value: float) -> None:
        self.dct[key] = float(value)


class Step(Protocol):
    """
    Class storing information for a step.
    """

    input_suffixes: Sequence[str]
    output_suffix: str
    config: Any

    def run(self, input_file: Path) -> Path: ...


def copy_file(
    input_files: Iterable[Path], dest_folder: Path
) -> Generator[Path, None, None]:
    for input_file in input_files:
        if not input_file.is_file():
            raise FileNotFoundError(f"Input file {input_file} not found.")
        dest_folder.mkdir(parents=True, exist_ok=True)
        dst = dest_folder / input_file.name
        if not dst.is_file():
            shutil.copy(input_file, dst)
        yield dst


def init_step(dimensions: Dim, base_dir: Path) -> Path:
    output_file = base_dir / "top.json"
    if output_file.is_file():
        with output_file.open("r") as f:
            ref = json.load(f)
        if ref == dimensions.dct:
            return output_file
    with output_file.open("w") as f:
        json.dump(dimensions.dct, f)
    return output_file


def validate_input(input_file: Path, valid_suffixes: Sequence[str]) -> None:
    if input_file.suffix not in valid_suffixes:
        raise ValueError(f"{input_file} suffix is not in {valid_suffixes}")


def can_skip(input_file: Path, output_file: Path):
    if not output_file.is_file():
        return False
    if input_file.stat().st_mtime >= output_file.stat().st_mtime:
        logging.info(
            f"{input_file.name} is newer than {output_file.name}. Update needed, running full flow."
        )
        return False
    return True


def compose(*steps: Step, reload: bool = True) -> Step:
    class Compose:
        input_suffixes: Sequence[str]
        output_suffix: str
        config: Any

        def __init__(self, config: dict[str, Any]):
            self.input_suffixes = steps[0].input_suffixes
            self.output_suffix = steps[-1].output_suffix
            self.config = config

        def run(self, input_file: Path) -> Path:
            def fun(path: Path, step: Step) -> Path:
                validate_input(path, step.input_suffixes)
                excepted_output = path.with_suffix(step.output_suffix)
                if self.config["reload"] and can_skip(path, excepted_output):
                    return excepted_output
                return step.run(path)

            return reduce(fun, steps, input_file)

    return Compose({"reload": reload})


def cleanup(folder: str = "", dry_run: bool = False):
    """
    Remove all files generated by haadic in the specified folder.

    :param folder: path of the folder to clean.
    :param dry_run: if True, only print which files would be removed without actually removing them. Default is False.
    """
    suffix_to_remove = [".gds", ".cir", ".raw", ".log", ".nodes", ".sim", ".tcl"]
    if folder:
        os.chdir(Path(folder))
    for suffix in suffix_to_remove:
        file = Path("top").with_suffix(suffix)
        if file.is_file():
            if dry_run:
                print(f"Would remove file: {file}")
            else:
                os.remove(file)
    directories_to_remove = [
        "extfile",
    ]
    for directory in directories_to_remove:
        dir_path = Path(directory)
        if dir_path.is_dir():
            if dry_run:
                print(f"Would remove directory: {dir_path}")
            else:
                shutil.rmtree(dir_path)


def compare_to(perf: dict, target: dict):
    cost = 0
    for key in target:
        if perf is None or key not in perf:
            logging.warning(f"Key {key} not found in performance dictionary")
            cost += target[key] ** 2
        else:
            cost += (target[key] - perf[key]) ** 2

    return cost


def import_or_default(
    source: Path, to_be_loaded: Iterable[str] | str
) -> dict[str, Any]:
    if isinstance(to_be_loaded, str):
        to_be_loaded = set(to_be_loaded)

    imp_d = dict()
    for name in to_be_loaded:
        source = Path(source)
        if str(source.parent.absolute()) not in sys.path:
            sys.path.append(str(source.parent.absolute()))
        src_name = str(source.stem)
        imp = __import__(src_name, fromlist=name).__dict__
        if imp.get(name, None) is not None:
            imp_d[name] = imp[name]
    logging.debug(f"Imported design from {source}: {imp_d.keys()}")
    return imp_d
