
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  python-version: "3.12"

permissions:
  contents: read

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/ruff-action@v3
        with:
          args: 'check'        
      - uses: astral-sh/ruff-action@v3
        with:
          args: 'format --check'

  doc-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.python-version }}
          cache: 'pip'
      - run: |
          pip install --upgrade pip
          uv sync --only-group doc
      - name: Build Doc
        run: |
          uv run mkdocs build
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          path: site/

  testing:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    needs: [check-format, doc-build]

    steps:
    - uses: actions/checkout@v7
    - uses: Vampire/setup-wsl@v7
      if: ${{runner.os == 'Windows' }}
    - name: Install Nix for windows
      if: ${{runner.os == 'Windows' }}
      run: |
        Invoke-WebRequest https://github.com/nix-community/NixOS-WSL/releases/download/2505.7.0/nixos.wsl -OutFile ./nixos.wsl
        wsl --install --from-file .\nixos.wsl -n
        wsl --list
        Set-ExecutionPolicy -Scope CurrentUser Unrestricted # fix pdk installation error
    - name: Install Nix for Ubuntu
      if: ${{runner.os != 'Windows' }}
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-24.11
    - name: Config Ubuntu - Setup External Tools
      if: ${{runner.os != 'Windows' }}
      run: |
        nix-channel --update
        nix-channel --list
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ env.python-version }}
    - name: Install Dependencies
      run: |
        uv tree
        uv sync --group dev
    - name: Install PDK
      run: |
        uv run haadic pdk install sky130
        uv run haadic pdk install sky130
        uv run haadic pdk install gf180mcu
        uv run haadic pdk install gf180mcu
        uv run haadic pdk install asap7
        uv run haadic pdk list
    - name: Test with Pytest
      run: |
        uv run poe cover
    - name: Store reports
      if: failure()
      uses: actions/upload-artifact@v7
      with:
        name: reports-${{ matrix.os }}
        path: |
          tmp/
          pytest.log
          .coverage

  deploy:
    if:
      github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: [testing, doc-build]
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
